# Testing for the loss:

In [2]:
import numpy as np
from sklearn.cross_decomposition import CCA
import pandas as pd
import matplotlib.pyplot as plt
import random
import torch
import torch.nn as nn
from linear_cca import linear_cca
from torch.utils.data import BatchSampler, SequentialSampler
from DeepCCAModels import DeepCCA
from main import Solver
from utils import load_data, svm_classify
from objectives import cca_loss
try:
    import cPickle as thepickle
except ImportError:
    import _pickle as thepickle
import pickle
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
import sklearn.model_selection as model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import pprint

In [39]:
U = np.random.random_sample(1000).reshape(250,4)
V = np.random.random_sample(2000).reshape(250,8)

In [67]:
n_comps = 2
cca = CCA(n_components=n_comps)
U_c, V_c = cca.fit_transform(U, V)

print(U_c.shape)
print(V_c.shape)
result1 = np.corrcoef(U_c.T, V_c.T).diagonal(offset=n_comps)

l_cca = linear_cca()
l_cca.fit(U,V,n_comps)
result2 = np.corrcoef(l_cca.w[0], l_cca.w[1]).diagonal(offset=n_comps)


(250, 2)
(250, 2)


In [72]:
print(U_c.shape)
print(l_cca.w[0])

(250, 2)
[[-0.71332072  2.7072226 ]
 [-0.99586308 -1.44816906]
 [ 2.28904399  1.5038527 ]
 [-2.44727386  1.06529966]]


In [69]:
print(result1)
print(result2)

[0.26388644 0.18864053]
[[ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.  1. -1. -1. -1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]
 [ 1. -1. -1.  1. -1. -1.  1. -1. -1.  1.  1.  1.]]
